version: "2"

services:
  pasarela:
    restart: always
    build:
      context: .
      dockerfile_inline: |
        FROM nginx
        COPY conf/nginx-pasarela-front.conf /etc/nginx/templates/default.conf.template
        COPY conf/nginx-pasarela-api.conf /etc/nginx/locations/api.conf

  frontend:
    image: barquitos_frontend
    restart: always
    build:
      context: .
      dockerfile_inline: |
        FROM node:14 AS barquitos_angular
        RUN npm install -g @angular/cli@^14.0.0
        COPY frontend frontend
        WORKDIR /frontend
        RUN ng build
        FROM nginx
        COPY --from=barquitos_angular /frontend/dist /usr/share/nginx/html
        COPY conf/frontend-nginx.conf /etc/nginx/conf.d/default.conf
        COPY conf/frontend-angular.sh /docker-entrypoint.d/25-envsubst-on-frontend.sh

  php:
    image: barquitos_php
    restart: always
    build:
      context: .
      dockerfile_inline: |
        FROM php:apache
        COPY backend/api /var/www/html/api
        COPY conf/msmtprc /etc/msmtprc
        RUN docker-php-ext-install pdo pdo_mysql mysqli
        RUN apt update && apt upgrade -y && apt install -y mailutils msmtp msmtp-mta

  mysql:
    restart: always
