version: "2"

configs:
  pasarela_front:
    file: ./conf/nginx-pasarela-front.conf
  pasarela_api:
    file: ./conf/nginx-pasarela-api.conf
  pasarela_phpmyadmin_conf:
    file: ./conf/nginx-pasarela-phpmyadmin.conf
  php_msmtp:
    file: ./conf/msmtprc

services:
  pasarela:
    configs:
      - source: pasarela_front
        target: /etc/nginx/templates/default.conf.template
      - source: pasarela_api
        target: /etc/nginx/locations/api.conf
      - source: pasarela_phpmyadmin_conf
        target: /etc/nginx/locations/phpmyadmin.conf

  frontend:
    image: barquitos_frontend_dev
    build:
      context: .
      dockerfile_inline: |
        FROM node:14 AS barquitos_angular
        RUN npm install -g envsub
        RUN npm install -g @angular/cli@^14.0.0
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: >
      sh -c "envsub
      /frontend/src/assets/config.js.template
      /frontend/src/assets/config.js &&
      ng serve --disable-host-check --host 0.0.0.0 --port 80"

  php:
    image: barquitos_php_dev
    configs:
      - source: php_msmtp
        target: /etc/msmtprc
    build:
      context: .
      dockerfile_inline: |
        FROM php:apache
        RUN docker-php-ext-install pdo pdo_mysql mysqli
        RUN apt update && apt upgrade -y && apt install -y mailutils msmtp msmtp-mta
    volumes:
      - ./backend/api:/var/www/html/api
      - ./phpmyadmin:/var/www/html/phpmyadmin
