<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.1 setup script
 * Date: Wed, 20 Mar 2024 01:00:14 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: BBDD - Juego de los Barquitos [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'BBDD - Juego de los Barquitos';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['ssl'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = \sodium_hex2bin('9e16e9bc0ae7f6488a4cae0e4354ef3a3a4ca1b817704b97872308a61d5bba1a');
$cfg['DefaultLang'] = 'es';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

